export const productData = [
  {
    "favorite": "false",
    "name": "Inname openbaar domein voor een wielerwedstrijd",
    "description": "Inname van het openbaar domein voor de organisatie van een sportwedstrijd met nationale en internationale uitstraling",
    "Startdatum dienstverlening": "",
    "Einddatum dienstverlening": "nvt",
    "categorie": "Toelating",
    "Thema(’s)": "Andere organisatie, Burger, Lokaal bestuur",
    "Meer thema’s": "geen match",
    "Laatst gewijzigd": "2023-04-17",
    "Aangemaakt op": "2022-05-05",
    "Procedure": "Procedure (U kunt zoeken op naam van de gemeente, provincie, OCMW of een Antwerps district.In de databank kunt u de volgende gegevens van de mandatarissen raadplegen:naam van de mandatarisde kieslijst waartoe hij of zij behoorthet mandaat in kwestiede eventuele (geplande) termijn van het mandaat.de bevoegdheden van de burgemeester, schepenen of gedeputeerdenOp het tweede blad 'Administratieve gegevens' vindt u de contactgegevens van het bestuur. Voor gemeenten vindt u er ook nog:de namen van de (adjunct-)secretaris, de financieel beheerder en de informatieambtenaarde politiezone.De lokale besturen zijn decretaal verplicht om via de Mandatendatabank de Vlaamse Regering binnen de 20 dagen op de hoogte te brengen van eedafleggingen van mandatarissen. Die informatieplicht geldt ook voor wijzigingen in de samenstelling van het bestuur.De lokale besturen kunnen zelf hun gegevens aanpassen via een beveiligde toegang tot de databank.De link naar de Mandatendatabank en meer informatie over het beheer vindt u op de website Lokaalbestuur.vlaanderen.be.)",
    "Bewijsstukken": "",
    "Kosten": "",
    "Financieel voordeel": "",
    "Uitzonderingen": "",
    "Bevoegde bestuursniveau’s": "Vlaamse overheid",
    "Bevoegde organisaties": "https://wegwijs.vlaanderen.be/#/organisations/OVO001835",
    "Uitvoerende bestuursniveau’s": "Vlaamse overheid",
    "Uitvoerende organisaties": "",
    "link": "#!",
    "Regelgeving": "",
    "Links naar Vlaamse codex": "",
    "Productnummer": "2229",
    "Tags": "",
    "Zoektermen": "",
    "Publicatiekanalen": "",
    "Your Europe categorieën": "",
    "Publicatielink": "Lees meer op vlaanderen.be, https://www.vlaanderen.be/Product/d23043c6-6e09-4797-bf41-3ec427d923eb",
    "Verwante producten": "",
    "Deminimis": "ongekend",
    "Gestructureerde voorwaarden": "",
    "Subsidiemaatregel": "",
    "u/je versie": "31.8.0",
    "Gearchiveerd": "false",
    "Conceptnummer": "",
    "Geografische toepassingsgebieden": "Vlaams Gewest (BE2)",
    "Laatst ontvangen": "2024-01-30",
    "Contactgegevens": "",
    "filter": "tools",
    "filterTheme": "burger"
  },
  {
    "name": "Drankvergunning vaste drankgelegenheid",
    "description": "Als uitbater van een vaste drankgelegenheid (bijvoorbeeld een café, restaurant of cafetaria) heb je een drankvergunning nodig voor het schenken van alcoholhoudende dranken voor consumptie ter plaatse. Het gaat daarbij om gegiste dranken (bijvoorbeeld bier, wijn en mousserende wijn) en sterke drank (bijvoorbeeld gin, cognac en cocktails). De vergunning is persoons- en plaatsgebonden en kan niet worden overgedragen.",
    "link": "#!",
    "categorie": "Toelating",
  },
  {
    "name": "Toelating voor ambulante activiteit op private plaatsen langs de openbare weg en op commerciële parkings",
    "description": "Bij de uitbating van een kraam op privédomein is er sprake van een ambulante activiteit als er op dat adres geen vestigingseenheid in de KBO is geregistreerd en als het kraam aan de openbare weg grenst of geplaatst wordt op een commerciële parking. Voor die ambulante activiteit op privédomein is een toelating van de gemeente nodig. In andere gevallen is er sprake van een geregistreerd verkooppunt en geen ambulante activiteit, waardoor er geen toelating van de gemeente nodig is. ",
    "link": "#!",
    "categorie": "Toelating",
  },
  {
    "name": "Terrasvergunning - Inname openbaar domein",
    "description": "Voor het plaatsen van een horecaterras op het openbaar domein, vraag je als uitbater een terrasvergunning aan bij de gemeente. Het betreft de plaatsing van losse tafels en stoelen, parasols… voor zover die elementen makkelijk weg te nemen zijn en constructief geen geheel vormen. ",
    "link": "#!",
    "categorie": "Toelating",
  },
  {
    "name": "Toelating om bij een evenement af te wijken van het geluidsniveau ",
    "description": "Organiseer je een evenement met elektronische versterkte muziek dan moet je de geluidsnormen naleven. Wil je de muziek luider spelen dan de opgelegde geluidsnormen, dan kan je hiervoor een afwijking van de geluidsnormen aanvragen bij het college van burgemeester en schepenen.",
    "link": "#!",
    "categorie": "Toelating",
  },
  {
    "name": "Organisatie van een rommelmarkt, tweedehandsbeurs of collectieve garageverkoop",
    "description": "Op een rommelmarkt, tweedehandsbeurs of collectieve garageverkoop verkopen particulieren tweedehandsgoederen. Nieuwe of geproduceerde producten mogen ze er niet verkopen.",
    "link": "#!",
    "categorie": "Toelating",
  },
  {
    "name": "Permanente bewegwijzering van een onderneming ",
    "description": "Ondernemingen kunnen een aanvraag indienen om langs de openbare weg permanente wegwijzers te plaatsen naar hun onderneming. De wegbeheerder beoordeelt de aanvraag. Voor gemeentewegen is de gemeente bevoegd, voor gewestwegen is het Agentschap Wegen en Verkeer bevoegd.",
    "link": "#!",
    "categorie": "Toelating",
  }
]
