export const productData = [
  {
    "favorite": "false",
    "name": "Inname openbaar domein voor een wielerwedstrijd",
    "description": "Raadpleeg en hergebruik de gegevens van lokale mandatarissen in deze publiek toegankelijke mandatendatabank",
    "Startdatum dienstverlening": "",
    "Einddatum dienstverlening": "nvt",
    "categorie": "Vergunning",
    "Thema(’s)": "Andere organisatie, Burger, Lokaal bestuur",
    "Meer thema’s": "geen match",
    "Laatst gewijzigd": "2023-04-17",
    "Aangemaakt op": "2022-05-05",
    "Procedure": "Procedure (U kunt zoeken op naam van de gemeente, provincie, OCMW of een Antwerps district.In de databank kunt u de volgende gegevens van de mandatarissen raadplegen:naam van de mandatarisde kieslijst waartoe hij of zij behoorthet mandaat in kwestiede eventuele (geplande) termijn van het mandaat.de bevoegdheden van de burgemeester, schepenen of gedeputeerdenOp het tweede blad 'Administratieve gegevens' vindt u de contactgegevens van het bestuur. Voor gemeenten vindt u er ook nog:de namen van de (adjunct-)secretaris, de financieel beheerder en de informatieambtenaarde politiezone.De lokale besturen zijn decretaal verplicht om via de Mandatendatabank de Vlaamse Regering binnen de 20 dagen op de hoogte te brengen van eedafleggingen van mandatarissen. Die informatieplicht geldt ook voor wijzigingen in de samenstelling van het bestuur.De lokale besturen kunnen zelf hun gegevens aanpassen via een beveiligde toegang tot de databank.De link naar de Mandatendatabank en meer informatie over het beheer vindt u op de website Lokaalbestuur.vlaanderen.be.)",
    "Bewijsstukken": "",
    "Kosten": "",
    "Financieel voordeel": "",
    "Uitzonderingen": "",
    "Bevoegde bestuursniveau’s": "Vlaamse overheid",
    "Bevoegde organisaties": "https://wegwijs.vlaanderen.be/#/organisations/OVO001835",
    "Uitvoerende bestuursniveau’s": "Vlaamse overheid",
    "Uitvoerende organisaties": "",
    "link": "https://mandaten.lokaalbestuur.vlaanderen.be/",
    "Regelgeving": "",
    "Links naar Vlaamse codex": "",
    "Productnummer": "2229",
    "Tags": "",
    "Zoektermen": "",
    "Publicatiekanalen": "",
    "Your Europe categorieën": "",
    "Publicatielink": "Lees meer op vlaanderen.be, https://www.vlaanderen.be/Product/d23043c6-6e09-4797-bf41-3ec427d923eb",
    "Verwante producten": "",
    "Deminimis": "ongekend",
    "Gestructureerde voorwaarden": "",
    "Subsidiemaatregel": "",
    "u/je versie": "31.8.0",
    "Gearchiveerd": "false",
    "Conceptnummer": "",
    "Geografische toepassingsgebieden": "Vlaams Gewest (BE2)",
    "Laatst ontvangen": "2024-01-30",
    "Contactgegevens": "",
    "filter": "tools",
    "filterTheme": "burger"
  }
]
